import React, { useState, useEffect, useMemo } from "react";
import ReactDOM from 'react-dom';
import '../../../GlobalForm.css';
import '../../../GlobalOverlay.css';
import '../../../Global.css';
import ConfirmationModal from '../ConfirmationModal';

function AddSection({
  onClose,
  onSuccess,
  programId,
  programName,
  programAbbr,
  sectionToEdit = null,
}) {
  const isEditMode = !!sectionToEdit;

  const [sectionOption, setSectionOption] = useState("new");
  const [sectionNumber, setSectionNumber] = useState("");
  const [selectedSectionId, setSelectedSectionId] = useState("");
  const [yearLevel, setYearLevel] = useState("");
  const [semesterId, setSemesterId] = useState("");
  const [academicYearId, setAcademicYearId] = useState("");
  const [adviserId, setAdviserId] = useState("");
  const [isActive, setIsActive] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [academicYears, setAcademicYears] = useState([]);
  const [faculties, setFaculties] = useState([]);
  const [existingSections, setExistingSections] = useState([]);
  const [portalRoot, setPortalRoot] = useState(document.getElementById('portal-root') || document.body);
  const [confirmState, setConfirmState] = useState({ isOpen: false });
  const [successState, setSuccessState] = useState({ isOpen: false });

  const autoGeneratedName = useMemo(() => {
    if (!programAbbr) return "";

    let result = programAbbr;

    if (yearLevel) {
      result += ` ${yearLevel}`;
    }

    if (semesterId) {
      const semNumber = semesterId === '1' ? '1' : semesterId === '2' ? '2' : '3';
      result += `-Y${semNumber}`;
    }

    if (sectionNumber) {
      result += `-${sectionNumber}`;
    }

    return result;
  }, [programAbbr, yearLevel, semesterId, sectionNumber]);

  const closeConfirm = () => setConfirmState({ isOpen: false });

  const openAlert = (title, summary, variant = 'info') => {
    setConfirmState({
      isOpen: true,
      title,
      summary,
      variant,
      isAlert: true,
      onConfirm: closeConfirm,
      onCancel: closeConfirm,
    });
  };

  const showSuccess = (title, summary) => {
    setSuccessState({ isOpen: true, title, summary, variant: 'success' });
  };

  // --- Populate fields when editing ---
  useEffect(() => {
    if (!sectionToEdit) return;

    setSectionOption("existing");
    setSelectedSectionId(sectionToEdit.section_id?.toString() || "");
    setYearLevel(sectionToEdit.year_level?.toString() || "");
    setSemesterId(sectionToEdit.semester_id?.toString() || "");
    setAcademicYearId(
      (sectionToEdit.year_id ?? sectionToEdit.academic_year_id)?.toString() || ""
    );
    setAdviserId(sectionToEdit.adviser_id?.toString() || "");
    setIsActive(sectionToEdit.is_active !== false);

    if (sectionToEdit.section_number != null) {
      setSectionNumber(String(sectionToEdit.section_number));
    }
  }, [sectionToEdit]);

  useEffect(() => {
    const fetchData = async () => {
      const token = sessionStorage.getItem('token') || localStorage.getItem('token');
      const headers = { 'Authorization': `Bearer ${token}` };

      try {
        const yearsRes = await fetch(`${process.env.REACT_APP_API_URL}/admin/academic-years`, { headers });
        const yearsData = await yearsRes.json();
        if (yearsData.success) setAcademicYears(yearsData.data);
      } catch (error) {
        console.error("Error fetching academic years:", error);
      }

      try {
        const facultiesRes = await fetch(`${process.env.REACT_APP_API_URL}/admin/faculties`, { headers });
        const facultiesData = await facultiesRes.json();
        if (facultiesData.success) setFaculties(facultiesData.data);
      } catch (error) {
        console.error("Error fetching faculties:", error);
      }

      try {
        const sectionsRes = await fetch(`${process.env.REACT_APP_API_URL}/admin/sections/all?program_id=${programId}`, { headers });
        const sectionsData = await sectionsRes.json();
        if (sectionsData.success) setExistingSections(sectionsData.data);
      } catch (error) {
        console.error("Error fetching sections:", error);
      }
    };

    fetchData();
  }, [programId]);

  const handleSubmit = async () => {
    if (!isEditMode) {
      if (sectionOption === "new") {
        if (!sectionNumber) {
          openAlert('Missing Fields', 'Please enter section number.', 'warning');
          return;
        }
        if (!yearLevel || !semesterId || !academicYearId) {
          openAlert('Missing Fields', 'Please fill in all required fields.', 'warning');
          return;
        }
      }

      if (sectionOption === "existing" && !selectedSectionId) {
        openAlert('Missing Selection', 'Please select a section.', 'warning');
        return;
      }
    }

    if (!academicYearId) {
      openAlert('Missing Field', 'Please select academic year.', 'warning');
      return;
    }

    setIsSubmitting(true);

    try {
      const token = sessionStorage.getItem('token') || localStorage.getItem('token');

      const url = isEditMode
        ? `${process.env.REACT_APP_API_URL}/admin/section-assignments/${sectionToEdit.assignment_id}`
        : `${process.env.REACT_APP_API_URL}/admin/section-assignments`;

      const method = isEditMode ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
        section_option: sectionOption,
        section_name: sectionOption === "new" ? autoGeneratedName : null,
        section_number: sectionOption === "new" ? parseInt(sectionNumber) : null,
        section_id: selectedSectionId || null,
        program_id: programId,
        year_level: yearLevel ? parseInt(yearLevel) : null,
        semester_id: semesterId ? parseInt(semesterId) : null,
        year_id: parseInt(academicYearId),
        adviser_id: adviserId ? parseInt(adviserId) : null,
        is_active: isActive
      })
      });

      const data = await response.json();

      if (data.success) {
        showSuccess(
          isEditMode ? 'Section Updated' : 'Section Assignment Added',
          isEditMode
            ? 'The section assignment has been updated successfully.'
            : 'The section assignment has been added successfully.'
        );
      } else {
        openAlert(
          isEditMode ? 'Update Failed' : 'Creation Failed',
          data.message || 'Failed to save section assignment.',
          'danger'
        );
      }
    } catch (error) {
      console.error("Error saving section assignment:", error);
      openAlert('Connection Error', 'An unexpected error occurred. Please try again.', 'danger');
    } finally {
      setIsSubmitting(false);
    }
  };

  const modalContent = (
    <div className="modalOverlay">
      <div className="modalContainer">

        <div className="modalHeader">
          <h3 className="modalTitle">
            {isEditMode ? "UPDATE SECTION ASSIGNMENT" : "ADD SECTION ASSIGNMENT"}
          </h3>
          <div className="CloseBtnArea">
            <button className="CloseBtn" onClick={onClose} disabled={isSubmitting}>&times;</button>
          </div>
        </div>

        <div className="modalScrollArea">
          <div className="FormContent">

            {/* Section option dropdown — only when creating */}
            {!isEditMode && (
              <div className="formGroup">
                <label className="formLabel">SECTION OPTION <span style={{color: 'red'}}>*</span></label>
                <select
                  value={sectionOption}
                  onChange={(e) => setSectionOption(e.target.value)}
                  className="formSelect"
                >
                  <option value="new">Create New Section</option>
                  <option value="existing">Use Existing Section</option>
                </select>
              </div>
            )}

            {/* Edit mode: show the section name as read-only */}
            {isEditMode ? (
              <div className="formGroup">
                <label className="formLabel">SECTION</label>
                <input
                  type="text"
                  value={sectionToEdit.section_name || ""}
                  disabled
                  className="readOnlyInput"
                />
              </div>
            ) : sectionOption === "new" ? (
              <>
                <div className="formRow">
                  <div className="formGroup">
                    <label className="formLabel">YEAR LEVEL <span style={{color: 'red'}}>*</span></label>
                    <select
                      value={yearLevel}
                      onChange={(e) => setYearLevel(e.target.value)}
                      className="formSelect"
                    >
                      <option value="">Select Year Level</option>
                      <option value="1">1st Year</option>
                      <option value="2">2nd Year</option>
                      <option value="3">3rd Year</option>
                      <option value="4">4th Year</option>
                      <option value="5">5th Year</option>
                    </select>
                  </div>

                  <div className="formGroup">
                    <label className="formLabel">SEMESTER <span style={{color: 'red'}}>*</span></label>
                    <select
                      value={semesterId}
                      onChange={(e) => setSemesterId(e.target.value)}
                      className="formSelect"
                    >
                      <option value="">Select Semester</option>
                      <option value="1">1st Semester</option>
                      <option value="2">2nd Semester</option>
                      <option value="3">Summer Term</option>
                    </select>
                  </div>
                </div>

                <div className="formRow">
                  <div className="formGroup">
                    <label className="formLabel">SECTION NUMBER <span style={{color: 'red'}}>*</span></label>
                    <input
                      type="number"
                      placeholder="1"
                      min="1"
                      value={sectionNumber}
                      onChange={(e) => setSectionNumber(e.target.value)}
                    />
                  </div>
                  <div className="formGroup">
                    <label className="formLabel">SECTION NAME</label>
                    <input
                      type="text"
                      value={autoGeneratedName}
                      disabled
                      className="readOnlyInput"
                      placeholder="Will auto-generate"
                    />
                  </div>
                </div>
              </>
            ) : (
              <div className="formGroup">
                <label className="formLabel">EXISTING SECTION <span style={{color: 'red'}}>*</span></label>
                <select
                  value={selectedSectionId}
                  onChange={(e) => setSelectedSectionId(e.target.value)}
                  className="formSelect"
                >
                  <option value="">Select Section</option>
                  {existingSections.map(section => (
                    <option key={section.section_id} value={section.section_id}>
                      {section.section_name}
                    </option>
                  ))}
                </select>
              </div>
            )}

            <div className="formGroup">
              <label className="formLabel">ACADEMIC YEAR <span style={{color: 'red'}}>*</span></label>
              <select
                value={academicYearId}
                onChange={(e) => setAcademicYearId(e.target.value)}
                className="formSelect"
              >
                <option value="">Select Academic Year</option>
                {academicYears.map(year => (
                  <option key={year.year_id} value={year.year_id}>
                    {year.year_label} {year.is_active ? '(Current)' : ''}
                  </option>
                ))}
              </select>
            </div>

            <div className="formGroup">
              <label className="formLabel">ADVISER (Optional)</label>
              <select
                value={adviserId}
                onChange={(e) => setAdviserId(e.target.value)}
                className="formSelect"
              >
                <option value="">Select Adviser</option>
                {faculties.map(faculty => (
                  <option key={faculty.faculty_id} value={faculty.faculty_id}>
                    {faculty.first_name} {faculty.last_name} ({faculty.designation_name || 'Faculty'})
                  </option>
                ))}
              </select>
            </div>

            <div className="formGroup">
              <label className="formLabel">STATUS <span style={{color: 'red'}}>*</span></label>
              <div className="statusToggleContainer" onClick={() => setIsActive(!isActive)}>
                <div className={`statusSwitch ${isActive ? 'active' : 'inactive'}`}>
                  <div className="switchHandle"></div>
                </div>
                <span className={`statusLabel ${isActive ? 'text-active' : 'text-inactive'}`}>
                  {isActive ? "ACTIVE" : "INACTIVE"}
                </span>
              </div>
            </div>

            <div className="BtnsContainer">
              <button className="ResetFilterBtn" onClick={onClose} disabled={isSubmitting}>CANCEL</button>
              <button className="ApplyFilterBtn" onClick={handleSubmit} disabled={isSubmitting}>
                {isSubmitting
                  ? (isEditMode ? "UPDATING..." : "ADDING...")
                  : (isEditMode ? "UPDATE ASSIGNMENT" : "ADD ASSIGNMENT")}
              </button>
            </div>
          </div>
        </div>
      </div>

      <ConfirmationModal
        isOpen={successState.isOpen}
        title={successState.title}
        summary={successState.summary}
        variant={successState.variant}
        isAlert={true}
        onConfirm={() => {
          setSuccessState({ isOpen: false });
          onSuccess();
        }}
        onCancel={() => {
          setSuccessState({ isOpen: false });
          onSuccess();
        }}
      />

      <ConfirmationModal
        isOpen={confirmState.isOpen}
        title={confirmState.title}
        summary={confirmState.summary}
        variant={confirmState.variant}
        isAlert={confirmState.isAlert}
        onConfirm={confirmState.onConfirm}
        onCancel={confirmState.onCancel}
      />
    </div>
  );

  return ReactDOM.createPortal(modalContent, portalRoot);
}

export default AddSection;