import React, { useState, useEffect, useRef, useMemo } from "react";
import ReactDOM from 'react-dom';
import '../../GlobalForm.css'
import '../../GlobalOverlay.css';
import '../../Global.css';

function AddSection({ onClose, onSuccess, programId, programName, programAbbr }) {
  const [sectionOption, setSectionOption] = useState("new");
  const [sectionNumber, setSectionNumber] = useState("");
  const [selectedSectionId, setSelectedSectionId] = useState("");
  const [yearLevel, setYearLevel] = useState("");
  const [semesterId, setSemesterId] = useState("");
  const [academicYearId, setAcademicYearId] = useState("");
  const [adviserId, setAdviserId] = useState("");
  const [isActive, setIsActive] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [academicYears, setAcademicYears] = useState([]);
  const [faculties, setFaculties] = useState([]);
  const [existingSections, setExistingSections] = useState([]);
  const [portalRoot, setPortalRoot] = useState(document.getElementById('portal-root') || document.body);

  const autoGeneratedName = useMemo(() => {
    if (!programAbbr) return "";
    
    let result = programAbbr;
    
    if (yearLevel) {
      result += ` ${yearLevel}`;
    }
    
    if (semesterId) {
      const semNumber = semesterId === '1' ? '1' : semesterId === '2' ? '2' : '3';
      result += `-Y${semNumber}`;
    }
    
    if (sectionNumber) {
      result += `-${sectionNumber}`;
    }
    
    return result;
  }, [programAbbr, yearLevel, semesterId, sectionNumber]);

  useEffect(() => {
    const fetchData = async () => {
      const token = sessionStorage.getItem('token');
      const headers = { 'Authorization': `Bearer ${token}` };
      
      try {
        const yearsRes = await fetch(`${process.env.REACT_APP_API_URL}/admin/academic-years`, { headers });
        const yearsData = await yearsRes.json();
        if (yearsData.success) setAcademicYears(yearsData.data);
      } catch (error) {
        console.error("Error fetching academic years:", error);
      }
      
      try {
        const facultiesRes = await fetch(`${process.env.REACT_APP_API_URL}/admin/faculties`, { headers });
        const facultiesData = await facultiesRes.json();
        if (facultiesData.success) setFaculties(facultiesData.data);
      } catch (error) {
        console.error("Error fetching faculties:", error);
      }
      
      try {
        const sectionsRes = await fetch(`${process.env.REACT_APP_API_URL}/admin/sections/all?program_id=${programId}`, { headers });
        const sectionsData = await sectionsRes.json();
        if (sectionsData.success) setExistingSections(sectionsData.data);
      } catch (error) {
        console.error("Error fetching sections:", error);
      }
    };
    
    fetchData();
  }, [programId]);

  const handleSubmit = async () => {
    if (sectionOption === "new") {
      if (!sectionNumber) {
        alert("Please enter section number.");
        return;
      }
      if (!yearLevel || !semesterId || !academicYearId) {
        alert("Please fill in all required fields.");
        return;
      }
    }
    
    if (sectionOption === "existing" && !selectedSectionId) {
      alert("Please select a section.");
        return;
    }

    if (!academicYearId) {
      alert("Please select academic year.");
      return;
    }

    setIsSubmitting(true);

    try {
      const token = sessionStorage.getItem('token');
      const response = await fetch(`${process.env.REACT_APP_API_URL}/admin/section-assignments`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          section_option: sectionOption,
          section_name: sectionOption === "new" ? autoGeneratedName : null,
          section_number: sectionOption === "new" ? parseInt(sectionNumber) : null,
          section_id: selectedSectionId || null,
          program_id: programId,
          year_level: sectionOption === "new" ? parseInt(yearLevel) : null,
          semester_id: sectionOption === "new" ? parseInt(semesterId) : null,
          year_id: parseInt(academicYearId),
          adviser_id: adviserId ? parseInt(adviserId) : null,
          is_active: isActive
        })
      });

      const data = await response.json();

      if (data.success) {
        alert("Section assignment added successfully!");
        onSuccess();
      } else {
        alert(data.message || "Failed to add section assignment.");
      }
    } catch (error) {
      console.error("Error adding section assignment:", error);
      alert("An error occurred. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const modalContent = (
    <div className="modalOverlay">
      <div className="modalContainer">
        <div className="CloseBtnArea">
          <button className="CloseBtn" onClick={onClose} disabled={isSubmitting}>&times;</button>
        </div>
        <div className="modalHeader">
          <h3 className="modalTitle">ADD SECTION ASSIGNMENT</h3>
        </div>

        <div className="modalScrollArea">
          <div className="FormContent">
            <div className="formGroup">
              <label className="formLabel">SECTION OPTION <span style={{color: 'red'}}>*</span></label>
              <select 
                value={sectionOption} 
                onChange={(e) => setSectionOption(e.target.value)}
                className="formSelect"
              >
                <option value="new">Create New Section</option>
                <option value="existing">Use Existing Section</option>
              </select>
            </div>

            {sectionOption === "new" ? (
              <>
                <div className="formRow">
                  <div className="formGroup">
                    <label className="formLabel">YEAR LEVEL <span style={{color: 'red'}}>*</span></label>
                    <select 
                      value={yearLevel} 
                      onChange={(e) => setYearLevel(e.target.value)}
                      className="formSelect"
                    >
                      <option value="">Select Year Level</option>
                      <option value="1">1st Year</option>
                      <option value="2">2nd Year</option>
                      <option value="3">3rd Year</option>
                      <option value="4">4th Year</option>
                      <option value="5">5th Year</option>
                    </select>
                  </div>

                  <div className="formGroup">
                    <label className="formLabel">SEMESTER <span style={{color: 'red'}}>*</span></label>
                    <select 
                      value={semesterId} 
                      onChange={(e) => setSemesterId(e.target.value)}
                      className="formSelect"
                    >
                      <option value="">Select Semester</option>
                      <option value="1">1st Semester</option>
                      <option value="2">2nd Semester</option>
                      <option value="3">Summer Term</option>
                    </select>
                  </div>
                </div>

                <div className="formRow">
                  <div className="formGroup">
                    <label className="formLabel">SECTION NUMBER <span style={{color: 'red'}}>*</span></label>
                    <input 
                      type="number" 
                      placeholder="1"
                      min="1"
                      value={sectionNumber}
                      onChange={(e) => setSectionNumber(e.target.value)}
                    />
                  </div>
                  <div className="formGroup">
                    <label className="formLabel">SECTION NAME</label>
                    <input 
                      type="text" 
                      value={autoGeneratedName}
                      disabled
                      className="readOnlyInput"
                      placeholder="Will auto-generate"
                    />
                  </div>
                </div>
              </>
            ) : (
              <div className="formGroup">
                <label className="formLabel">EXISTING SECTION <span style={{color: 'red'}}>*</span></label>
                <select 
                  value={selectedSectionId} 
                  onChange={(e) => setSelectedSectionId(e.target.value)}
                  className="formSelect"
                >
                  <option value="">Select Section</option>
                  {existingSections.map(section => (
                    <option key={section.section_id} value={section.section_id}>
                      {section.section_name}
                    </option>
                  ))}
                </select>
              </div>
            )}

            <div className="formGroup">
              <label className="formLabel">ACADEMIC YEAR <span style={{color: 'red'}}>*</span></label>
              <select 
                value={academicYearId} 
                onChange={(e) => setAcademicYearId(e.target.value)}
                className="formSelect"
              >
                <option value="">Select Academic Year</option>
                {academicYears.map(year => (
                  <option key={year.year_id} value={year.year_id}>
                    {year.year_label} {year.is_active ? '(Current)' : ''}
                  </option>
                ))}
              </select>
            </div>

            <div className="formGroup">
              <label className="formLabel">ADVISER (Optional)</label>
              <select 
                value={adviserId} 
                onChange={(e) => setAdviserId(e.target.value)}
                className="formSelect"
              >
                <option value="">Select Adviser</option>
                {faculties.map(faculty => (
                  <option key={faculty.faculty_id} value={faculty.faculty_id}>
                    {faculty.first_name} {faculty.last_name} ({faculty.designation_name || 'Faculty'})
                  </option>
                ))}
              </select>
            </div>

            <div className="formGroup">
              <label className="formLabel">STATUS <span style={{color: 'red'}}>*</span></label>
              <div className="statusToggleContainer" onClick={() => setIsActive(!isActive)}>
                <div className={`statusSwitch ${isActive ? 'active' : 'inactive'}`}>
                  <div className="switchHandle"></div>
                </div>
                <span className={`statusLabel ${isActive ? 'text-active' : 'text-inactive'}`}>
                  {isActive ? "ACTIVE" : "INACTIVE"}
                </span>
              </div>
            </div>

            <div className="BtnsContainer">
              <button className="ResetFilterBtn" onClick={onClose} disabled={isSubmitting}>CANCEL</button>
              <button className="ApplyFilterBtn" onClick={handleSubmit} disabled={isSubmitting}>
                {isSubmitting ? "ADDING..." : "ADD ASSIGNMENT"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );

  return ReactDOM.createPortal(modalContent, portalRoot);
}

export default AddSection;